language: node_js
node_js:
- 4.1.1
- 4
- 5
env:
  global:
    secure: W4EHA6bMyZIiRHDHCx/eZCOkYhq80/EsYTKulISiLwByNBnMPE6H0ckfeKcV7johhc/tuTCtEkDn97MZw8JF+WmqBcE9MOKziW3IOKsw/RsHkviJYkC9zn+ubSlBGhiqsjLsaaqWJv9VF0xJiIkR8cdwQBnqXu9PXOL1jxiC1zFjkCzoYpfBMA6L4SvEaQ4yrvrge7xkoJHkFh0rs7qCIjyHp90+kwfI0TgF3WyGFJt+0OHH1DslWgj7LiZtGcMiPgEK/3F+C41bbIBYBZN6wfOj0BsOmUx3Gk8bomMxk2Fk8EfbnFPCKVK0Yf1Lf98Yord0pniTyRBMwsLcTGxLuzapqPYeJl35koX8CFDoQ/LkgtLYgeZSPc5w+kbwGlXLOLau5mQtfKdyI+vPgYjJ5LKwfoD++Oe1zS5cgCT/tucjmfcURVRV4QSNGnwitF1Z6GhTfqp6zUAB1ZfDVBfmin5aESYOc77QDUn/Z2xhaVF6w09WtK66rpsWLSqctXcOuSdprv6YzUgql6umho5ji0IHZa7KOap4c7HSCPLVnnKzzwQhkNKDy6R/J9ymTJxv3wG1hTpr4Wf0W+nd/twgsflI0UfHQA3YCHYaRddrJqhgcPriuZ6vNEqx7x12itPtQ1yW5funrB8BjfWrBIpGvrVA8kqK7fiJCq2Y6cXskU4=
